### ISSUE TITLE
Underscore as an explicit dependency

### ISSUE THREAD

**Issue by Fabs** [hwillson/meteor-stub-collections#1]
First of all thanks for the package :). 

I am getting this error, I believe it was because I did not have underscore installed. 
```
Error: Cannot read property 'bind' of null
    at Function._.bind (packages/underscore/underscore.js:627:1)
    at packages/hwillson:stub-collections/stub_collections.js:44:11
    at Array.forEach (/Users/fabs/.meteor/packages/es5-shim/.4.5.10.1xv5zig++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object._private.stubPair (packages/hwillson:stub-collections/stub_collections.js:40:22)
    at packages/hwillson:stub-collections/stub_collections.js:24:18
    at Array.forEach (/Users/fabs/.meteor/packages/es5-shim/.4.5.10.1xv5zig++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object._public.stub (packages/hwillson:stub-collections/stub_collections.js:15:35)
    at Context.<anonymous> (server/methods/players.tests.js:20:21)
    at run (packages/practicalmeteor:mocha/meteor/src/setup/SetupRunnables.js:113:18)
```

I took a look at the source, this line uses underscore, it looks weird to me. I tried running **meteor add underscore** and restarting my test server, still not running.

After some refreshes on the webpage running practicalmeteor:mocha driver, I get also this error on sinon.stub.
```
Error: Attempted to wrap _makeNewID which is already wrapped
    at checkWrappedMethod (packages/practicalmeteor_sinon.js:1244:29)
    at Object.wrapMethod (packages/practicalmeteor_sinon.js:1285:21)
    at Object.stub (packages/practicalmeteor_sinon.js:3185:26)
    at packages/hwillson:stub-collections/stub_collections.js:41:13
    at Array.forEach (/Users/fabs/.meteor/packages/es5-shim/.4.5.10.1xv5zig++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object._private.stubPair (packages/hwillson:stub-collections/stub_collections.js:40:22)
    at packages/hwillson:stub-collections/stub_collections.js:24:18
    at Array.forEach (/Users/fabs/.meteor/packages/es5-shim/.4.5.10.1xv5zig++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object._public.stub (packages/hwillson:stub-collections/stub_collections.js:15:35)
    at Context.<anonymous> (server/methods/players.tests.js:20:21)
--------------
Error: Stack Trace for original
    at Object.wrapMethod (packages/practicalmeteor_sinon.js:1304:34)
    at Object.stub (packages/practicalmeteor_sinon.js:3185:26)
    at packages/hwillson:stub-collections/stub_collections.js:41:13
    at Array.forEach (/Users/fabs/.meteor/packages/es5-shim/.4.5.10.1xv5zig++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object._private.stubPair (packages/hwillson:stub-collections/stub_collections.js:40:22)
    at packages/hwillson:stub-collections/stub_collections.js:24:18
    at Array.forEach (/Users/fabs/.meteor/packages/es5-shim/.4.5.10.1xv5zig++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object._public.stub (packages/hwillson:stub-collections/stub_collections.js:15:35)
    at Context.<anonymous> (server/methods/players.tests.js:20:21)
    at run (packages/practicalmeteor:mocha/meteor/src/setup/SetupRunnables.js:113:18)
```

I have Meteor 1.3.2.4 and my packages are
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

standard-minifier-css
standard-minifier-js
semantic:ui-css
blaze-html-templates
simple:rest
meteortoys:allthings
accounts-facebook
meteorhacks:kadira
stylus
accounts-ui-unstyled
practicalmeteor:mocha
xolvio:cleaner
dburles:factory
aldeed:simple-schema
hwillson:stub-collections
underscore
practicalmeteor:chai
practicalmeteor:sinon
```

**Comment by hwillson** [comment]
Hi @Fabs - thanks for the issue; I'll take a look and get back to you shortly.

**Comment by Fabs** [comment]
Thanks. Also maybe my title is now misleading. When I first wrote the issue I though the "meteor add underscore" would solve it, but it did not, also when I checked the package.js, I noticed there is "underscore" on the api.use. 

Anyway, if you know what needs to be done but do not have time to do it, I could try to help with a PR. 

Thanks for your work 👍

**Comment by hwillson** [comment]
No problem @Fabs, I can take a look. So are you still seeing the `Cannot read property 'bind' of null` error, the `Attempted to wrap _makeNewID which is already wrapped`, or both? I don't see the same issues when I run the package tests so something must be conflicting somewhere. Can you give me an example of how you're calling `StubCollections.add/stub` and `StubCollections.restore` (some sample code from one of your tests would be great).

**Comment by Fabs** [comment]
For instance, this test on a single sample.tests.js
```
/* eslint prefer-arrow-callback: "off" */
/* eslint import/no-unresolved: [2, { ignore: ["meteor"]}] */

import {expect} from 'meteor/practicalmeteor:chai';
import {sinon} from 'meteor/practicalmeteor:sinon';
import {Meteor} from 'meteor/meteor';
import {grantPointsBatch} from './players.js';
import StubCollections from 'meteor/hwillson:stub-collections';
import Players from '/imports/api/collections/players.js';

describe('testing some method', function() {
  before(function() {
    StubCollections.stub(Players);
  });

  after(function() {
    StubCollections.restore();
  });

  it('call my method', function() {
    expect(true).to.equal(true);
  });
});
```

if I just ctrl+c then run the  `meteor test -p 4001 --driver-package practicalmeteor:mocha` I get this:

![image](https://cloud.githubusercontent.com/assets/10524/15027301/86b5d846-1219-11e6-9f0c-93186ba7b102.png)

If I reload the page, this:
![image](https://cloud.githubusercontent.com/assets/10524/15027318/9d20cd3e-1219-11e6-9bf5-5070f13f49e6.png)

I just played around now, if the code is instead:
` before(function() {
    StubCollections.add(Players);
    StubCollections.stub();
  });`

it works:
![image](https://cloud.githubusercontent.com/assets/10524/15027355/c32f1738-1219-11e6-8b65-48435de94b47.png)

**Comment by Fabs** [comment]
I think I have a hunch. I was testing without this package stubs, with a code similar to this one:
````
describe('some testing', function() {
  describe('that was here...', function() {
    beforeEach(function() {
      sinon.stub(Meteor, 'user', () => ({
        userId: Random.id(),
        profile: {name: 'Casper'},
      }));
    });

    afterEach(function() {
      sinon.restore();
    });

    it('some test', function() {
      //do_not_exist();
      expect(true).to.equal(false);
    });
  });
});
````

And I got the following error, when I reloaded the page after uncommenting the **do_not_exist();**
![image](https://cloud.githubusercontent.com/assets/10524/15032323/0d498b52-1236-11e6-8703-cf0370f7a3ca.png)

It appeared to me that because something went wrong during a test run, the sinon was never restored, and the next attempt to stub the same method, caused an error. (the wrap of the already wrapped). When I added the sandbox like this:

````
const sandbox = sinon.sandbox.create();
describe('some testing', function() {
  describe('that was here...', function() {
    beforeEach(function() {
      sandbox.stub(Meteor, 'user', () => ({
        userId: Random.id(),
        profile: {name: 'Casper'},
      }));
    });

    afterEach(function() {
      sandbox.restore();
    });

    it('some test', function() {
      do_not_exist();
      expect(true).to.equal(false);
    });
  });
});
````

It works all the time even during refreshes.

**Comment by hwillson** [comment]
Great, thanks @Fabs - I've merged your changes in and will aim to get a new version published shortly. Thanks again!

**Comment by hwillson** [comment]
1.0.1 is now published. Closing this off - thanks!
