### ISSUE TITLE
_ensureIndex causes crash

### ISSUE THREAD

**Issue by cunneen** [hwillson/meteor-stub-collections#26]
If the collection I'm stubbing has a call to _ensureIndex (as per [How to optimize your Mongo database for Meteor.js](http://joshowens.me/how-to-optimize-your-mongo-database-for-meteor-js/) , I get the following error

```Uncaught Error: Can only call _ensureIndex on server collections```

```
at Mongo.Collection._ensureIndex (packages/mongo/collection.js:651:11)
at Object.invoke (.meteor/packages/hwillson_stub-collections/.1.0.6.1i286aa.gv4e++os+web.browser+web.cordova/npm/node_modules/sinon/lib/sinon/behavior.js:150:32)
at Mongo.Collection.functionStub (.meteor/packages/hwillson_stub-collections/.1.0.6.1i286aa.gv4e++os+web.browser+web.cordova/npm/node_modules/sinon/lib/sinon/stub.js:98:47)
at Function.invoke (.meteor/packages/hwillson_stub-collections/.1.0.6.1i286aa.gv4e++os+web.browser+web.cordova/npm/node_modules/sinon/lib/sinon/spy.js:193:47)
at Mongo.Collection.proxy [as _ensureIndex] (.meteor/packages/hwillson_stub-collections/.1.0.6.1i286aa.gv4e++os+web.browser+web.cordova/npm/node_modules/sinon/lib/sinon/spy.js:73:57)
```

**Comment by evg1n** [comment]
Hello,

I had the same issue, you should check whether you invoke this function on the server or on the client side. It must be invoked on the server side.

```
Meteor.startup( () => {
  SomeCollection._ensureIndex({
    "_id": 1
  });

  SomeCollectionTwo._ensureIndex({
    "_id": 1
  });
});
```

this is my perfectly working `collectionIndex.js` file, it is under
`../imports/startup/server/collectionIndexes/` folder.

I hope this helps.

Cheers.

**Comment by cunneen** [comment]
Thanks! I've actually no recollection of posting the above issue.
